name: floating_windows
description: A widget wrapper that allows a floating widget be dragged and rescaled.
version: 1.0.0
homepage: https://github.com/papatutu/floating_windows
repository: https://github.com/papatutu/floating_windows
issue_tracker: https://github.com/papatutu/floating_windows/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ">=7.2.1 < 9.0.0"
  logging: ">=1.0.2 < 2.0.0"
  equatable: ">=2.0.3 < 3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:

